### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by unixninja92** [ColumbiaDVMM/ColumbiaImageSearch#1]
Please include a license for the project. In the DARPA catalog this project is listed as BSD licensed but there is no indication of that in the repo.

**Comment by generalmilk** [comment]
Hi Charles,

Thanks for reminding us.  

Hi Svebor, in case you cannot see this email, I forward it to you. 
Thanks,

Best Regards,

Tao Chen

**Comment by svebk** [comment]
Thanks for the reminder. Fixed in 879c959f4be9fcfe895cfb9bc8411cb1f2fa6848
